### ISSUE TITLE
alternative foldRight for Streams

### ISSUE THREAD

**Issue by k0ala** [fpinscala/fpinscala#425]
Am I doing something wrong here?

https://github.com/k0ala/fpinscala/blob/master/exercises/src/main/scala/fpinscala/laziness/Stream.scala#L126

Seems simpler than the current answer, but I am not sure it does exactly the same.

https://github.com/fpinscala/fpinscala/blob/master/answers/src/main/scala/fpinscala/laziness/Stream.scala#L180

**Comment by runarorama** [comment]
Looks like your `scanRight` will only work for infinite streams. And it's going to be quite strict in the tail. Consider `cons(true, sys.error("oops")).scanRight(0)((a, b) => if (a) 1 else b)`.

**Comment by k0ala** [comment]
Unless I am mistaken, the solution provided in the answers throws on that as well :)

**Comment by runarorama** [comment]
You _are_ mistaken :)

```
scala> cons(true, sys.error("oops")).scanRight(0)((a, b) => if (a) 1 else b)
res0: fpinscala.laziness.Stream[Int] = Cons(<function0>,<function0>)

scala> res0.take(1).toList
res1: List[Int] = List(1)
```

**Comment by k0ala** [comment]
That's odd, I get a different behavior (using the provided answer):

```
scala> import fpinscala.laziness._
import fpinscala.laziness._

scala> Stream.cons(true, sys.error("oops")).scanRightAnswer(0)((a, b) => if (a) 1 else b)
res0: fpinscala.laziness.Stream[Int] = Cons(<function0>,<function0>)

scala> res0.take(1).toList
java.lang.RuntimeException: oops
  at scala.sys.package$.error(package.scala:27)
  at $anonfun$2.apply(<console>:13)
  at $anonfun$2.apply(<console>:13)
  at fpinscala.laziness.Stream$.tail$lzycompute$1(Stream.scala:145)
  at fpinscala.laziness.Stream$.fpinscala$laziness$Stream$$tail$1(Stream.scala:145)
  at fpinscala.laziness.Stream$$anonfun$cons$2.apply(Stream.scala:146)
  at fpinscala.laziness.Stream$$anonfun$cons$2.apply(Stream.scala:146)
  at fpinscala.laziness.Stream$$anonfun$foldRight$1.apply(Stream.scala:15)
  at fpinscala.laziness.Stream$$anonfun$scanRightAnswer$2.p1$lzycompute$1(Stream.scala:134)
  at fpinscala.laziness.Stream$$anonfun$scanRightAnswer$2.fpinscala$laziness$Stream$class$$anonfun$$p1$1(Stream.scala:134)
  at fpinscala.laziness.Stream$$anonfun$scanRightAnswer$2$$anonfun$apply$9.apply(Stream.scala:136)
  at fpinscala.laziness.Stream$$anonfun$scanRightAnswer$2$$anonfun$apply$9.apply(Stream.scala:136)
  at fpinscala.laziness.Stream$.tail$lzycompute$1(Stream.scala:145)
  at fpinscala.laziness.Stream$.fpinscala$laziness$Stream$$tail$1(Stream.scala:145)
  at fpinscala.laziness.Stream$$anonfun$cons$2.apply(Stream.scala:146)
  at fpinscala.laziness.Stream$$anonfun$cons$2.apply(Stream.scala:146)
  at fpinscala.laziness.Stream$$anonfun$take$1.apply(Stream.scala:31)
  at fpinscala.laziness.Stream$$anonfun$take$1.apply(Stream.scala:31)
  at fpinscala.laziness.Stream$class.toList(Stream.scala:8)
  at fpinscala.laziness.Cons.toList(Stream.scala:140)
  ... 43 elided
```

**Comment by runarorama** [comment]
Have you pulled the latest source? I'd check that your `cons` is not strict in its second argument, and that `scanRightAnswer` matches the provided code exactly.






—

**Comment by k0ala** [comment]
I found the problem. It was actually my `take` that wasn't lazy in the `n==1` case. Apologies.

**Comment by woofyzhao** [comment]
I have an alternative that seems to eliminate the tuple for z:
`    def scanRight1[B](z: B)(f: (A, => B) => B): Stream[B] = {
      foldRight(Stream.cons(z, Empty))((a, s) => {
        lazy val y = s
        y match {
          case Cons(h, _) => Stream.cons(f(a, h()), y)
          case _ => Empty
        }
      })
    }
`
Is this also correct?
