### ISSUE TITLE
NullPointerException on launching sbt

### ISSUE THREAD

**Issue by vidhyapg** [fpinscala/fpinscala#548]
on running sbt.cmd in Windows from both command prompt and git bash I get the following error

[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at java.base/java.util.regex.Pattern.split(Unknown Source)
        at sbt.IO$.pathSplit(IO.scala:797)
        at sbt.IO$.parseClasspath(IO.scala:912)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
        at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
        at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
        at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
[error] (compile:compileIncremental) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

**Comment by vidhyapg** [comment]
updating to latest SBT resolved this issue for me.

**Comment by muthupal007** [comment]
I had the same and I did the same fix as you did as well. That worked for running the sbt but for compiling the exercise, I'm getting the following error. Did you get the same ?

sbt:exercises> compile
[info] Updating ...
[info] Done updating.
[info] Compiling 22 Scala sources to /Users/mkaruppayya/fpinscala/exercises/target/scala-2.12/classes ...
[error] /Users/mkaruppayya/fpinscala/exercises/src/main/scala/fpinscala/parsing/Parsers.scala:28:39: value drop is not a member of java.util.stream.Stream[String]
[error]     if (input.length > 1) input.lines.drop(line-1).next
[error]                                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Oct 24, 2018, 10:23:34 AM
